PYTHON = python3

all: stage0 stage1 stage2 stage3 stage4 stage5

stage0:
	$(PYTHON) stage0.py

stage1:
	$(PYTHON) stage1.py

stage2:
	$(PYTHON) stage2.py

stage3:
	$(PYTHON) stage3.py

stage4:
	$(PYTHON) stage4.py

stage5:
	$(PYTHON) stage5.py

main:
	$(PYTHON) main.py


